### PR TITLE
feat: Support for Pulse 4.0.0-beta.1

### PR DESCRIPTION
**Pull request by lukeredpath**
* Bumps SPM package version
* Fixes tests

Probably not something to merge in until 4.0.0 is final but as I needed to switch to 4.0 and we use this I thought I'd make a branch for myself and others to use in the meantime.

### CODE REVIEW

**Comment by kean** [comment]
Thanks, @lukeredpath. If you've tried Pulse for Mac or there is something you'd like to see in Pulse 4.0, please let me know!

**Comment by lukeredpath** [comment]
I have, I’ve submitted a few bugs/enhancement requests via TestFlight. Thanks.

**Comment by hugovanderlei** [comment]
@kean Can this PR be merged? I'm getting a dependency error after updating Pulse 4.0

**Comment by kean** [comment]
I pushed version [4.0.0](https://github.com/kean/PulseLogHandler/releases/tag/4.0.0). I appreciate @lukeredpath's work on this repo!

**Pull request merged**
